print('\t\t "Welcome to India Voting System Registration Window!" \t\t ')
FirstName = str(input("Enter Applicant First Name: "))
LastName = str(input("Enter Applicant Last Name: "))
D_O_B = str(input("Enter Applicant Date of Birth (DD/MM/YYYY): "))
Gender = str(input("Enter Applicant Gender: "))
Mobile = str(input("Enter Applicant Mobile Number: "))
Email = str(input("Enter Applicant Email Address: "))
Aadhar_Number = str(input("Enter Applicant Aadhar Number: "))
Address = str(input("Enter Applicant Address: "))
print("\n\t\tThank You For Providing Your Information! \t\t")
print("\n\t\tYour Details Are As Follows: \t\t")
print(f"First Name: {FirstName}")
print(f"Last Name: {LastName}")
print(f"Date of Birth: {D_O_B}")
print(f"Gender: {Gender}")
print(f"Mobile Number: {Mobile}")
print(f"Email Address: {Email}")
print(f"Aadhar Number: {Aadhar_Number}")
print(f"Address: {Address}")
print("\n\t\tWe Will Contact You Soon! Have a Great Day! \t\t")
end = input("Press Enter to Close the Window.")
