print ('Hello Mr. Rahul, Welcome to Python Programming')
print ('This is my first Python Program')
print ('I am learning Python Programming Language')
print ('Python is a great programming language')
print ('I am enjoying learning Python')
print ('I will not give up learning Python from very basic to advanced and became a Python Developer very soon with the knowledge of How to train AI LLM')
print ('----Poem on Python Programming Language----')
print ("The Serpent of Logic")
print ('In the hush of a midnight screen,')
print("a serpent coils in lines unseen,")
print("its scales are loops, its breath is light,")
print("it dreams in code through endless night.")
print("Indentation—soft as sand,")
print("guides the flow like a patient hand;")
print("no braces bite, no clutter binds,")
print("just clarity in ordered minds.")
print("It speaks in truths both terse and clear,")
print("each function shaped to draw you near;")
print("from list to dict, from class to thread,")
print("it weaves the paths where logic’s led.")
print("Yet in its heart, a poet dwells,")
print("in every if a story swells;")
print("and when the final script is run,")
print("it hums—machine and mind as one.")