a = 1995
b = 21

print("Sum of Numbers:", a + b)
print("Difference of Numbers:", a - b)
print("Product of Numbers:", a * b)
print("Quotient of Numbers:", a / b)
print("Remainder of Numbers:", a % b)
print("Exponentiation of Numbers:", a ** b)
print("Floor Division of Numbers:", a // b)
print("Absolute Value of a:", abs(a))
print("Absolute Value of b:", abs(b))
print("Maximum of a and b:", max(a, b))
print("Minimum of a and b:", min(a, b))
print("Rounded Value of a:", round(a))
print("Rounded Value of b:", round(b))
print("Integer Value of a:", int(a))
print("Integer Value of b:", int(b))
print("Floating Point Value of a:", float(a))
print("Floating Point Value of b:", float(b))
print("Power of a to b:", pow(a, b))
print("Square Root of a:", a ** 0.5)
print("Square Root of b:", b ** 0.5)
print("Logarithm of a to base 10:", a ** (1/10))
print("Logarithm of b to base 10:", b ** (1/10))
