print("      Welcome to the Basic Entry Forum!      ")
Name = str(input("Please enter your name: "))
DOB = str(input("Please enter your date of birth (DD/MM/YYYY): "))
Gender = str(input("Please enter your gender: "))
Mbile_Number = str(input("Please enter your mobile number: "))
Email = str(input("Please enter your email address: "))
Address = str(input("Please enter your address: "))

print("\n Hello, " + Name + "! Thank you for providing your information!      ")
print("\n\t\tYour details are as follows: ")
print("Name: " + Name)
print("Date of Birth: " + DOB)
print("Gender: " +  Gender)
print("Mobile Number: " + Mbile_Number)             
print("Email: " + Email)
print("Address: " + Address)
print("\n\t\tWe Will Contact You Soon! Have a Great Day!")
end = input("Press Enter to exit the program.")
